spin_manifest_version = 2

[application]
name = "openai-wasm"
version = "0.1.0"
authors = ["Daniel Heinze <daheinze@microsoft.com>"]
description = ""

[[trigger.http]]
route = "/"
component = "healthcheck"

[[trigger.http]]
route = "/api/openai"
component = "openai"

[component.healthcheck]
source = "target/wasm32-wasi/release/openai_wasm.wasm"
allowed_outbound_hosts = []

[component.healthcheck.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.openai]
source = "target/wasm32-wasi/release/openai_wasm.wasm"
allowed_outbound_hosts = ["https://random-data-api.fermyon.app:443"]

[component.openai.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]