spin_manifest_version = 2

[application]
name = "openai-wasm"
version = "0.1.0"
authors = ["Daniel Heinze <daheinze@microsoft.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "openai-wasm"

[component.openai-wasm]
source = "target/wasm32-wasi/release/openai_wasm.wasm"
allowed_outbound_hosts = []
[component.openai-wasm.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
